#!/bin/bash

echo "Let us pretend that this is building something ... and takes 20 seconds"

count=0
while [ "$count" -lt 20 ]; do
    count=$((count + 1))

    color_code=$((31 + (count % 7)))
    printf "\e[01;${color_code}mBuilding [$count of 20]\e[00m\n"

    sleep 1
done

cat >my-artifact.html <<EOF
<html>
<body>
<h3>An example artifact</h3>
<pre>
==== ==== ====
An example artifact, created on: $(date)

Pipeline which created it: $GO_PIPELINE_NAME
Pipeline counter was: $GO_PIPELINE_COUNTER
==== ==== ====
</pre>
<br>
<h2>Calcular comissao vendedor</h2>
<input type="text" id="sale" value=""/>
<input type="button" onClick="calc()"  value="Calcular Comissao"/>
<div id="result"></div>
<script>
  function calc(){
        var x = parseFloat(document.getElementById("sale").value);
        var y = 0.02;
        var teste = x * y;
        document.getElementById("result").innerHTML = "";
        document.getElementById("result").innerHTML = teste;
  }
</script>
</body>
</html>
EOF
